#!/usr/bin/env python3

from contextlib import contextmanager
import os
import os.path as path
import shutil
import subprocess
import sys
import tempfile


EXTENSIONS = [
    ".tar", ".tgz", ".tar.gz", ".tar.bz2", ".tbz", ".tbz2",
    ".tar.xz", ".tar.lzma", ".tlz", ".tar.Z",
]


@contextmanager
def changing_dir(d):
    curdir = os.getcwd()
    os.chdir(d)
    try:
        yield
    finally:
        os.chdir(curdir)


@contextmanager
def temp_directory():
    name = tempfile.mkdtemp()
    try:
        yield name
    finally:
        shutil.rmtree(name)


@contextmanager
def archive_mount(dira, tara):
    exit_code = subprocess.call(['archivemount', tara, dira])
    if exit_code != 0:
        sys.exit(exit_code)
    try:
        yield
    finally:
        subprocess.call(['fusermount', '-u', dira])


@contextmanager
def archive_expand(dira, tara):
    exit_code = subprocess.call(['tar', 'xf', tara, '-C', dira])
    if exit_code != 0:
        sys.exit(exit_code)
    yield


__doc__ = """{f}: diff between two .tar files.
Recognized tar file extensions are: {extensions}

Usage:
  {f} -r <options>... <tar1> <tar2>
  {f} --git <options>... <tar1> <tar2>

Options:
  --git     Use `git diff` instead of `diff`.
  --tar     Use `tar` to expand files to temporary directory.

All the other options will be passed through to `diff` command.
""".format(f=path.basename(__file__), extensions=', '.join(EXTENSIONS))


def main(argv):
    args = argv[1:]
    if not args:
        print(__doc__)
        return

    option_tar = False
    option_git = False
    options = []
    tar_files = []
    for a in args:
        for e in EXTENSIONS:
            if a.endswith(e):
                tar_files.append(a)
                break  # for e
        else:
            if a == '--git':
                option_git = True
            elif a == '--tar':
                option_tar = True
            else:
                options.append(a)

    if len(tar_files) != 2:
        sys.exit("error: must specify two tar files")
    for t in tar_files:
        if not path.isfile(t):
            sys.exit("error: no such file: %s" % t)

    with temp_directory() as temp_dir:
        dira = path.join(temp_dir, 'a')
        os.mkdir(dira)
        dirb = path.join(temp_dir, 'b')
        os.mkdir(dirb)

        mount_func = archive_expand if option_tar else archive_mount
        with mount_func(dira, tar_files[0]):
            with mount_func(dirb, tar_files[1]):
                with changing_dir(temp_dir):
                    diff = ['git', 'diff'] if option_git else ['diff']
                    exit_code = subprocess.call(diff + options + ['a', 'b'])
                sys.exit(exit_code)


if __name__ == '__main__':
    main(sys.argv)
